<?php

namespace App\Http\Requests\Service;

use App\Http\Requests\AppRequest;
use Illuminate\Foundation\Http\FormRequest;

class ServiceRequest extends AppRequest
{
    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

}
